version: "3.3"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  nodejs:
    build:
      context: .
      dockerfile: dockerfile
    image: node:14-alpine
    container_name: nodejs
    restart: unless-stopped
    ports:
      - "8080:8080"